# Generated by Django 4.1.4 on 2022-12-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
