# Generated by Django 4.1.4 on 2022-12-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
